// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUCW_cUN7nPocgUuxU0IYYfKC6ohT4XsA',
    appId: '1:398834852035:web:534467192582bd26664276',
    messagingSenderId: '398834852035',
    projectId: 'fast-app-65ffc',
    authDomain: 'fast-app-65ffc.firebaseapp.com',
    storageBucket: 'fast-app-65ffc.firebasestorage.app',
    measurementId: 'G-5EYDLZ8402',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLi25sVaVHusQ_mR4ern9TWZqmLoway0',
    appId: '1:398834852035:android:385c46a29bd80982664276',
    messagingSenderId: '398834852035',
    projectId: 'fast-app-65ffc',
    storageBucket: 'fast-app-65ffc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWWVrYl8P-xzDzJRanGnfN5c28n7w72Z8',
    appId: '1:398834852035:ios:99cef50b90ad05d8664276',
    messagingSenderId: '398834852035',
    projectId: 'fast-app-65ffc',
    storageBucket: 'fast-app-65ffc.firebasestorage.app',
    iosBundleId: 'com.example.fl',
  );
}
